#!/bin/bash

# Author : Bilal Elmoussaoui, Andreas Angerer
# Version : 0.1
# Licence : The script is released under GPL

USERNAME=${SUDO_USER:-$USER}
DATABASE_FILE="database.csv"
# Desktop directory path
desktop_dir="$(sudo -u ${USERNAME} xdg-user-dir DESKTOP)/"

# Path's of .destkop files
applications_location=("/usr/share/applications/"
          "/usr/share/applications/kde4/"
          "/usr/share/applications/wine/"
          "/usr/local/share/applications/"
          "/usr/local/share/applications/kde4/"
          "/usr/local/share/applications/wine/"
          "/home/${USERNAME}/.local/share/applications/"
          "/home/${USERNAME}/.local/share/applications/kde4/"
          "/home/${USERNAME}/.local/share/applications/wine/"
          $desktop_dir)

# List of paths to not be saved as a copy (back up)
backup_ignore=( $desktop_dir )

#The script needs root privileges
if [ "$(id -u)" != "0" ]; then
  echo "You need to have root privileges to run the script."
  echo "Please try again,this time using 'sudo'. Exiting."
  exit 1
fi

if [ -z "$1" ]; then
  mode="apply"
else
  case $@ in
    -r|--revert)
      mode="revert";;
    -a|--apply)
      mode="apply";;
  esac
fi

if [[ "$@" == "--force-update" || "$@" == "-u" || ! -f $DATABASE_FILE ]]; then
  echo "Updating the database file.."
  wget "https://raw.githubusercontent.com/bil-elmoussaoui/StartupWMClassFixer/master/${DATABASE_FILE}" -O $DATABASE_FILE
  chown -R ${USERNAME} "./${DATABASE_FILE}"
fi

{
  read;
  while IFS=', ' read -r name launcher startup_wmclass; do
    for app_location in "${applications_location[@]}"
    do
      desktop_file="$app_location$launcher.desktop"
      backup_file="$desktop_file.bak"
      if [ "$mode" == "apply" ]; then
        if [ -f "$desktop_file" ]; then
          if ! grep -Pq "StartupWMClass\s*=\s*$startup_wmclass$" "$desktop_file"; then
            if [[ ! -f "$backup_file" && ! $app_location =~ $backup_ignore ]]; then
              cp "$desktop_file" "$backup_file"
            fi
            current_wmclass=$(grep "^StartupWMClass\s*=*" "$desktop_file"  | sed "s/StartupWMClass.*=//" | uniq)
            while read -r wm_class; do
              if [ -z "$wm_class" ]; then
                line_number=$(grep -n "^Exec\s*=*" "$desktop_file" |cut -f1 -d:)
                k=0
                while read -r i; do
                  j=$((i+k))
                  sed -i "${j}i\StartupWMClass=$startup_wmclass" "$desktop_file"
                  k=$((k+1))
                done <<< "$line_number"
              else
                sed -i "s#StartupWMClass\s*=\s*$wm_class#StartupWMClass=$startup_wmclass#g" "$desktop_file"
              fi
            done <<< "$current_wmclass"
            echo "Fixed : $name"
          fi
        fi
      elif [ "$mode" == "revert" ]; then
        if [[ -f "$desktop_file" && -f "$backup_file" && ! $app_location =~ $backup_ignore ]]; then
          mv "$backup_file" "$desktop_file"
          echo "Reverted : $name"
        fi
      fi
    done
  done
}< "${DATABASE_FILE}"
