#!/bin/bash

# Author : Bilal Elmoussaoui, Andreas Angerer
# Version : 0.1 beta
# Licence : The script is released under GPL

applications_location=("/usr/share/applications/"
          "/usr/local/share/applications/"
          "/usr/local/share/applications/kde4"
          "/home/${SUDO_USER:-$USER}/.local/share/applications/"
          "/home/${SUDO_USER:-$USER}/.local/share/applications/kde4/"
          $(xdg-user-dir DESKTOP))

backup_ignore=( $(xdg-user-dir DESKTOP) )

IFS=,

#The script needs root privileges
if [ "$(id -u)" != "0" ]; then
  echo "You need to have root privileges to run the script."
  echo "Please try again,this time using 'sudo'. Exiting."
  exit 1
fi

if [ ! -f "database.csv" ]; then
  wget https://github.com/bil-elmoussaoui/StartupWMClassFixer/blob/master/database.csv
fi

if [ -z "$1" ]; then
    mode="apply"
else
    case $1 in
        -r|--revert)
            mode="revert";;
        -a|--apply)
            mode="apply";;
    esac
fi

if [ "$mode" == "apply" ]; then
{
  read;
  while read -r name launcher startupwmclass; do
      for app_location in "${applications_location[@]}"
      do
        desktop_file="$app_location$launcher.desktop"
        backup_file="$desktop_file.bak"
        if [ -f "$desktop_file" ]; then
          if ! grep -Gq "StartupWMClass\s*=\s*$startupwmclass$" "$desktop_file"; then
            if [[ ! -f "$backup_file" && ! $app_location =~ $backup_ignore ]]; then
              cp "$desktop_file" "$backup_file"
            fi
            old_startup=$(grep "^StartupWMClass=*" "$desktop_file"  | sed "s/StartupWMClass.*=//")
            if [ -z "$old_startup" ]; then
              echo "StartupWMClass = $startupwmclass" >> "$desktop_file"
            else
              sed -i -- "s#$old_startup#$startupwmclass#g" "$desktop_file"
            fi
            echo "Fixed : $name"
          fi
        fi
      done
  done
}< "database.csv"
elif [ "$mode" == "revert" ]; then
{
  read;
  while read -r name launcher startupwmclass; do
      for app_location in "${applications_location[@]}"
      do
        desktop_file="$app_location$launcher.desktop"
        backup_file="$desktop_file.bak"
        if [[ -f "$desktop_file" && -f "$backup_file" && ! $app_location =~ $backup_ignore ]]; then
          mv "$backup_file" "$desktop_file"
          echo "Reverted : $name"
        fi
      done
  done
}< "database.csv"
fi
